#161779880 users are able to report articles.
andela/selene-ah-backend pull request #79
Opened 2018-12-20 14:55 UTC by gbols

#### What does this PR do?
it enables users to report articles.
#### Description of Task to be completed?

- It enables users to post report about articles.

- admin can query the reports of a specific article

- admin can query all the reports on the platform

#### How should this be manually tested?
git clone `ft-report-an-article-161779880 `
npm install
npm test
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
#[161779880](https://www.pivotaltracker.com/story/show/161779880)
#### Screenshots (if appropriate)
<img width="1440" alt="screen shot 2018-12-20 at 3 43 50 pm" src="https://user-images.githubusercontent.com/27724644/50291298-75c0e400-046e-11e9-8ea2-9e754fa5d579.png">

2018-12-20 17:06 UTC, davidshare approved these changes
LGTM

2018-12-21 09:52 UTC, VictoriaOffoma requested changes
findArticle sounds like a name of a function. Use something that shows the value contained in the variable e.g "article, reported article"

2018-12-21 15:09 UTC, VictoriaOffoma approved these changes

2018-12-21 15:09 UTC, VictoriaOffoma commented on server/controllers/reportArticleController.js
> +            if (!findArticle) {
Change the variable "findArticle" to something more descriptive like "article" or "reportedArticle".

2018-12-21 15:09 UTC, VictoriaOffoma commented on server/helpers/validationHelper.js
> +const isFieldValid = (input, length = 1) => {
The "isFieldValid" is not descriptive as it does not tell us what field is or what field refers to.

2018-12-21 15:09 UTC, merged